version: '3.9'

services:
  postgres_db:
    container_name: postgres_container
    image: "${POSTGRES_IMAGE:-postgres:latest}"
    environment:
      TZ: Etc/UTC
      POSTGRES_INITDB_ARGS: '--locale=en_US.UTF-8 --encoding=UTF8'
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ${POSTGRES_CONFIG_DIR:-./.config/postgres}/sql/30_postgres_initdb.sh:/docker-entrypoint-initdb.d/30_postgres_initdb.sh
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - env_net
    restart: always
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres} -h localhost"
        ]
      interval: 30s
      timeout: 5s
      retries: 3

  pgadmin:
    container_name: pgadmin_container
    image: "${PGADMIN_IMAGE:-dpage/pgadmin:latest}"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-SuperSecret}
      PGADMIN_CONFIG_SERVER_MODE: "${PGADMIN_CONFIG_SERVER_MODE:-True}"
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: "${PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED:-True}"
    volumes:
      - pgadmin:/var/lib/pgadmin
      - ${PGADMIN_CONFIG_DIR:-./.config/pgadmin4}/servers.json:/pgadmin4/servers.json
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - env_net
    restart: unless-stopped

networks:
  env_net:
    external: true

volumes:
  pgdata:
  pgadmin:
